### ISSUE TITLE
Micropython: Is the SD-Card working? 

### ISSUE THREAD

**Issue by jdede** [ComNets-Bremen/WUSN#11]

**Comment by Wolfestin123** [comment]
If you're encountering errors and have come across SD card designs in TI reference designs, it's worth noting that some of them may not include populated or mounted pull-up resistors for the SD_CLK signal. To troubleshoot the issue further, you can try disabling or removing the pull-up resistor associated with the SD_CLK signal. This can be done by unmounting the SD_CLK pull-up resistor from the circuit.

**Comment by FarukKollar** [comment]
Found problem in the Sd card connection in the schematics. Pin 7 and 8 was swapped according to reference designs. Corrected the pins. Afterwards checked with different size Sd cards to write and read, it works as expected. (Faruk&Karun)

**Comment by B00mb0x** [comment]
Works for MoleNetv6

**Comment by jdede** [comment]
Here is a MWE for MoleNetv6 & Python.

```
import machine, os
sd = machine.SDCard(slot=2, sck=machine.Pin(12), miso=machine.Pin(13), mosi=machine.Pin(11), cs=machine.Pin(10))
sd.info()
os.mount(sd, "/sd")
os.listdir('/sd')
os.umount("/sd")
```
